### PR TITLE
fix: fixed not found page for nl and de

### PR DESCRIPTION
**Pull request by alexanderhodes**

### CODE REVIEW

**Comment by alexanderhodes** [comment]
I've implemented a solution for the 404 page problem that worked in dev mode well, but not in production. For production we need a 404 in each language, therefore I've added a 404 for each language.
In dev mode, only `404.astro` in `pages` will be used. Therefore, I've implemented a check if environment is production to translate the page into the right language. [Here](https://docs.astro.build/en/guides/environment-variables/#_top) you can find the docs about the environment variables
```typescript
// hack that in production we always use english, but in development we use the current locale
const locale = import.meta.env.PROD ? "en" : Astro.currentLocale;

```
I've already tested it successfully in production

**Comment by kslstn** [comment]
Hey @alexanderhodes, thanks for that. What's the benefit of having this feature when it only works in dev mode? A drawback could be that a discrepancy between dev and prod may confuse developers.

For the rest of the starter I've aimed to use markdown files + layouts for adding translations where possible. In my experience, translations are often done on a per-page basis. A general strings file can quickly get unwieldy, so I'm trying to only use it for cross-page and site-wide strings. Using that approach, wouldn't markdown files calling the old 404 layout file achieve the same as the current solution?

**Comment by alexanderhodes** [comment]
@kslstn this feature works in both, production and dev mode. The previous solution with the translation in the 404.astro page with the Astro.locale integration worked in dev mode while runtime, but not in production, because there has been only a single `404.html` localized in the default language.
For getting this working, I've added the `404.astro` pushing the locale into the layout `404.astro`. This solution works well in production, because now we have an existing `404.html` for every language. The drawback is, that in dev mode while runtime only the english translation would be shown for 404. 
That's why I combined both solutions with the dynamic solution for runtime and the 404 files per language. This can be easily done by checking in the site is production using the Astro environment variables. In my point of view, there's no easier and more maintainable solution for having translated 404 pages in development and production. 
Using markdown files as layout and page would lead to the problem that it would work in production but not in development, because the `404.md` in the root pages folder would use the english translation

**Comment by kslstn** [comment]
Alright sounds good! But how is the server supposed to know what page to pick? The [demo on Netlify](https://astro-i18n-blog-starter.netlify.app/de/this%20page%20does%20not%20exist) only shows the English strings.

**Pull request merged**
